version: "3.9"

services:
  fastapi-connector:
    name: FastAPIConnector
    repository:
      url: https://github.com/jc230285/FastAPIConnector
      branch: main
    buildPack: dockerfile
    environment:
      OCR_URL: http://paddleocr:8866
      LLM_API: http://ollama:11434
    ports:
      - internal: 8000
        external: 5010
    depends_on:
      - paddleocr
      - ollama
    networks:
      - ai-net
    domains:
      - host: connector.yourdomain.com
        port: 5010
    restart: unless-stopped

  paddleocr:
    name: PaddleOCR
    image: thomaskuoch/paddleocr-docker:latest
    ports:
      - internal: 8866
        external: 8866
    restart: unless-stopped
    networks:
      - ai-net
    domains:
      - host: ocr.yourdomain.com
        port: 8866

  ollama:
    name: Ollama
    image: ollama/ollama:latest
    ports:
      - internal: 11434
        external: 11434
    volumes:
      - /data/ollama:/root/.ollama
    restart: unless-stopped
    networks:
      - ai-net
    domains:
      - host: ollama.yourdomain.com
        port: 11434

  openwebui:
    name: OpenWebUI
    image: ghcr.io/open-webui/open-webui:latest
    environment:
      OLLAMA_API_BASE: http://ollama:11434
    depends_on:
      - ollama
    ports:
      - internal: 8080
        external: 5000
    restart: unless-stopped
    networks:
      - ai-net
    domains:
      - host: ai.yourdomain.com
        port: 5000

networks:
  ai-net:
    driver: bridge